
package RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum CategoriaCoche
{
	// region - Literals

	Economico (1)
	,	Estandar (2)
	,	Lujo (3)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	CategoriaCoche (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static CategoriaCoche fromRawValue (int rawValue)
	{
		CategoriaCoche[] enumValues = CategoriaCoche.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
