//
// Enumerations.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation


enum CategoriaCoche: Int
{
	case Economico = 1
	case Estandar = 2
	case Lujo = 3
}

enum EstadoCoche: Int
{
	case Libre = 1
	case Alquilado = 2
}

	