	
		//
		// ClienteDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ClienteDTO 	    {
		 
				var dNI: String?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var direccion: String?;
				    	 
		 
				var telefono: String?;
				    	 
		 
				var factura_oid: [Int]?;
				    	 
		 
				var reserva_oid: [Int]?;
				    	 
		 
				var pass: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["dNI"] = self.dNI;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["direccion"] = self.direccion;
				

				
					dictionary["telefono"] = self.telefono;
				

					dictionary["factura_oid"] = self.factura_oid;
			

					dictionary["reserva_oid"] = self.reserva_oid;
			

				
					dictionary["pass"] = self.pass;
				
						
				return dictionary;
			}
		}
		
	