//
// ClienteRegistradoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class ClienteRegistradoDTOA : DTOA
{
	// MARK: - Properties

	var dNI: String?;
	
	var nombre: String?;
	var direccion: String?;
	var telefono: String?;
	
	/* Rol: ClienteRegistrado o--> Factura */
	var facturas: [FacturaDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.dNI = json["DNI"].object as? String
		
	
		self.nombre = json["Nombre"].object as? String;
		self.direccion = json["Direccion"].object as? String;
		self.telefono = json["Telefono"].object as? String;
		
		if (json["Facturas"] != JSON.null)
		{
			self.facturas = FacturaDTOA(fromJSONObject: json["Facturas"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["DNI"] = self.dNI;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Direccion"] = self.direccion;
	
	

	
		dictionary["Telefono"] = self.telefono;
	
	
		
		dictionary["Facturas"] = self.facturas?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	