//
// CocheDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CocheDTOA : DTOA
{
	// MARK: - Properties

	
	var numLicencia: Int?;
	var categoria: CategoriaCoche?;
	var estado: EstadoCoche?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.numLicencia = json["NumLicencia"].object as? Int;
		if let enumValue = json["Categoria"].object as? Int
		{
			self.categoria = CategoriaCoche(rawValue: enumValue);
		}
		if let enumValue = json["Estado"].object as? Int
		{
			self.estado = EstadoCoche(rawValue: enumValue);
		}
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["NumLicencia"] = self.numLicencia;
	
	

	
		dictionary["Categoria"] = self.categoria?.rawValue;
	
	

	
		dictionary["Estado"] = self.estado?.rawValue;
	
	
		
		
		
		return dictionary;
	}
}

	