//
// FacturaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class FacturaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var fecha: NSDate?;
	var esPagada: Bool?;
	var esAnulada: Bool?;
	
	/* Rol: Factura o--> LineaFactura */
	var lineas: [LineaFacturaDTOA]?;

	
	/* ServiceLink: dameTotal */
	var dameTotal: Double?;

	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		self.esPagada = json["EsPagada"].object as? Bool;
		self.esAnulada = json["EsAnulada"].object as? Bool;
		
		if (json["Lineas"] != JSON.null)
		{
			self.lineas = [];
			for subJson in json["Lineas"].arrayValue
			{
				self.lineas!.append(LineaFacturaDTOA(fromJSONObject: subJson));
			}
		}

		
		if (json["DameTotal"] != JSON.null)
		{
			self.dameTotal = FacturaDTOA(fromJSONObject: json["DameTotal"]);
		}
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["EsPagada"] = self.esPagada;
	
	

	
		dictionary["EsAnulada"] = self.esAnulada;
	
	
		
		dictionary["Lineas"] = NSNull();
		if (self.lineas != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.lineas!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["Lineas"] = arrayOfDictionary;
		}

		
		dictionary["DameTotal"] = self.dameTotal?.toDictionary() ?? NSNull();
		
		return dictionary;
	}
}

	