//
// LineaFacturaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class LineaFacturaDTOA : DTOA
{
	// MARK: - Properties

	
	var numLinea: Int?;
	var precio: Double?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.numLinea = json["NumLinea"].object as? Int;
		self.precio = json["Precio"].object as? Double;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["NumLinea"] = self.numLinea;
	
	

	
		dictionary["Precio"] = self.precio;
	
	
		
		
		
		return dictionary;
	}
}

	