//
// ReservaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class ReservaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var inicio: NSDate?;
	var final: NSDate?;
	
	/* Rol: Reserva o--> Coche */
	var coches: CocheDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
	
		self.inicio = NSDate.initFromString(json["Inicio"].object as? String);
	
		self.final = NSDate.initFromString(json["Final"].object as? String);
		
		if (json["Coches"] != JSON.null)
		{
			self.coches = CocheDTOA(fromJSONObject: json["Coches"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Inicio"] = self.inicio?.toString();
	
	

	
		dictionary["Final"] = self.final?.toString();
	
	
		
		dictionary["Coches"] = self.coches?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	