
package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTOA;

import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class ClienteAnonimoDTOA extends DTOA
{
	// region - Members, getters and setters

	private String dNI;
	public String getDNI () { return dNI; }
	public void setDNI (String dNI) { this.dNI = dNI; }

	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public ClienteAnonimoDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("DNI")))
			{
				this.dNI = (String) json.opt("DNI");
			}
			
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.dNI != null){
				json.put("DNI", this.dNI);
			}
			
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		ClienteDTO dto = new ClienteDTO ();
		
		// Attributes
		
	dto.setDNI (this.getDNI());

		
		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	