
package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTOA;

import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CocheDTOA extends DTOA
{
	// region - Members, getters and setters

	
	private Integer numLicencia;
	public Integer getNumLicencia () { return numLicencia; }
	public void setNumLicencia (Integer numLicencia) { this.numLicencia = numLicencia; }
	
	private CategoriaCoche categoria;
	public CategoriaCoche getCategoria () { return categoria; }
	public void setCategoria (CategoriaCoche categoria) { this.categoria = categoria; }
	
	private EstadoCoche estado;
	public EstadoCoche getEstado () { return estado; }
	public void setEstado (EstadoCoche estado) { this.estado = estado; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CocheDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			

			if (!JSONObject.NULL.equals(json.opt("NumLicencia")))
			{
			 
				this.numLicencia = (Integer) json.opt("NumLicencia");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Categoria")))
			{
				int enumRawValue = (int) json.opt("Categoria");
				this.categoria = CategoriaCoche.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Estado")))
			{
				int enumRawValue = (int) json.opt("Estado");
				this.estado = EstadoCoche.fromRawValue(enumRawValue);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			
		
		  if (this.numLicencia != null)
			json.put("NumLicencia", this.numLicencia.intValue());
		
		
		  if (this.categoria != null)
			json.put("Categoria", this.categoria.getRawValue());
		
		
		  if (this.estado != null)
			json.put("Estado", this.estado.getRawValue());
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CocheDTO dto = new CocheDTO ();
		
		// Attributes
		
		
	dto.setNumLicencia (this.getNumLicencia());

	dto.setCategoria (this.getCategoria());

	dto.setEstado (this.getEstado());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	