
package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTOA;

import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class LineaFacturaDTOA extends DTOA
{
	// region - Members, getters and setters

	
	private Integer numLinea;
	public Integer getNumLinea () { return numLinea; }
	public void setNumLinea (Integer numLinea) { this.numLinea = numLinea; }
	
	private Double precio;
	public Double getPrecio () { return precio; }
	public void setPrecio (Double precio) { this.precio = precio; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public LineaFacturaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			

			if (!JSONObject.NULL.equals(json.opt("NumLinea")))
			{
			 
				this.numLinea = (Integer) json.opt("NumLinea");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Precio")))
			{
			 
			 	String stringDouble = String.valueOf(json.opt("Precio"));
 				this.precio = Double.parseDouble(stringDouble);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			
		
		  if (this.numLinea != null)
			json.put("NumLinea", this.numLinea.intValue());
		
		
		  if (this.precio != null)
			json.put("Precio", this.precio);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		LineaFacturaDTO dto = new LineaFacturaDTO ();
		
		// Attributes
		
		
	dto.setNumLinea (this.getNumLinea());

	dto.setPrecio (this.getPrecio());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	