
package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTOA;

import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
import RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class ReservaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private java.util.Date inicio;
	public java.util.Date getInicio () { return inicio; }
	public void setInicio (java.util.Date inicio) { this.inicio = inicio; }
	
	private java.util.Date final;
	public java.util.Date getFinal () { return final; }
	public void setFinal (java.util.Date final) { this.final = final; }
	
	
	/* Rol: Reserva o--> Coche */
	private CocheDTOA coches;
	public CocheDTOA getCoches () { return coches; }
	public void setCoches (CocheDTOA coches) { this.coches = coches; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public ReservaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Inicio")))
			{
			 
			 	String stringDate = (String) json.opt("Inicio");
				this.inicio = DateUtils.stringToDateFormat(stringDate);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Final")))
			{
			 
			 	String stringDate = (String) json.opt("Final");
				this.final = DateUtils.stringToDateFormat(stringDate);
			 
			}
			

			JSONObject jsonCoches = json.optJSONObject("Coches");
			if (jsonCoches != null)
			{
				CocheDTOA tmp = new CocheDTOA();
				tmp.setFromJSON(jsonCoches);
				this.coches = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.inicio != null)
			json.put("Inicio", DateUtils.dateToFormatString(this.inicio));
		
		
		  if (this.final != null)
			json.put("Final", DateUtils.dateToFormatString(this.final));
		
			

			if (this.coches != null)
			{
				json.put("Coches", this.coches.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		ReservaDTO dto = new ReservaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setInicio (this.getInicio());

	dto.setFinal (this.getFinal());

		
		
		// Roles
					// TODO: from DTOA [ Coches ] (dataType : CocheDTOA) to DTO [ Coche ]
		
		
		return dto;
	}

	// endregion
}

	