	
		package RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO.utils.*;
		import  RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class FacturaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Boolean esPagada;
				public Boolean getEsPagada () { return esPagada; } 
				public void setEsPagada  (Boolean value) { esPagada = value;  } 
				    	 
				private Boolean esAnulada;
				public Boolean getEsAnulada () { return esAnulada; } 
				public void setEsAnulada  (Boolean value) { esAnulada = value;  } 
				    	 
				private String cliente_oid;
				public String  getCliente_oid () { return cliente_oid; } 
				public void setCliente_oid (String value) { cliente_oid = value;  } 
				    	 
				private ArrayList<LineaFacturaDTO> lineaFactura;
				public ArrayList<LineaFacturaDTO> getLineaFactura () { return lineaFactura; } 
				public void setLineaFactura (ArrayList<LineaFacturaDTO> value) { lineaFactura = value;  } 
				    	 
				private float total;
				public float getTotal () { return total; } 
				public void setTotal  (float value) { total = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
				
						  json.put("EsPagada", this.esPagada);
				
				
						  json.put("EsAnulada", this.esAnulada);
				

						if (this.cliente_oid != null)
						{
							json.put("Cliente_oid", this.cliente_oid);
						}

						if (this.lineaFactura != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.lineaFactura.size(); ++i)
							{
								jsonArray.put(this.lineaFactura.get(i).toJSON());
							}
							json.put("LineaFactura", jsonArray);
						}
				
						  json.put("Total", this.total);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	