	
		package RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO.utils.*;
		import  RentACarRESTGenAdminRentACarRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ProveedorDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private ArrayList<Integer> coche_oid;
				public ArrayList<Integer>  getCoche_oid () { return coche_oid; } 
				public void setCoche_oid (ArrayList<Integer> value) { coche_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.coche_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.coche_oid.size(); ++i)
							{
								jsonArray.put(this.coche_oid.get(i));
							}
							json.put("Coche_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	