	
		package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
		import  RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CocheDTO 	    implements IDTO
	    {
				private Integer reserva_oid;
				public Integer  getReserva_oid () { return reserva_oid; } 
				public void setReserva_oid (Integer value) { reserva_oid = value;  } 
				    	 
				private Integer numLicencia;
				public Integer getNumLicencia () { return numLicencia; } 
				public void setNumLicencia  (Integer value) { numLicencia = value;  } 
				    	 
				private CategoriaCoche categoria;
				public CategoriaCoche getCategoria () { return categoria; } 
				public void setCategoria  (CategoriaCoche value) { categoria = value;  } 
				    	 
				private EstadoCoche estado;
				public EstadoCoche getEstado () { return estado; } 
				public void setEstado  (EstadoCoche value) { estado = value;  } 
				    	 
				private ArrayList<Integer> proveedor_oid;
				public ArrayList<Integer>  getProveedor_oid () { return proveedor_oid; } 
				public void setProveedor_oid (ArrayList<Integer> value) { proveedor_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.reserva_oid != null)
						{
							json.put("Reserva_oid", this.reserva_oid.intValue());
						}
				
						  json.put("NumLicencia", this.numLicencia.intValue());
				
				
						  json.put("Categoria", this.categoria.getRawValue());
				
				
						  json.put("Estado", this.estado.getRawValue());
				

						if (this.proveedor_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.proveedor_oid.size(); ++i)
							{
								jsonArray.put(this.proveedor_oid.get(i));
							}
							json.put("Proveedor_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	