	
		package RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.utils.*;
		import  RentACarRESTGenRentACarRESTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class LineaFacturaDTO 	    implements IDTO
	    {
				private Integer factura_oid;
				public Integer  getFactura_oid () { return factura_oid; } 
				public void setFactura_oid (Integer value) { factura_oid = value;  } 
				    	 
				private Integer numLinea;
				public Integer getNumLinea () { return numLinea; } 
				public void setNumLinea  (Integer value) { numLinea = value;  } 
				    	 
				private Integer reserva_oid;
				public Integer  getReserva_oid () { return reserva_oid; } 
				public void setReserva_oid (Integer value) { reserva_oid = value;  } 
				    	 
				private Double precio;
				public Double getPrecio () { return precio; } 
				public void setPrecio  (Double value) { precio = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.factura_oid != null)
						{
							json.put("Factura_oid", this.factura_oid.intValue());
						}
				
						  json.put("NumLinea", this.numLinea.intValue());
				

						if (this.reserva_oid != null)
						{
							json.put("Reserva_oid", this.reserva_oid.intValue());
						}
				
						  json.put("Precio", this.precio);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	