	
		//
		// CocheDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CocheDTO 	    {
		 
				var reserva_oid: Int?;
				    	 
		 
				var numLicencia: Int?;
				    	 
		 
				var categoria: CategoriaCoche?;
				    	 
		 
				var estado: EstadoCoche?;
				    	 
		 
				var proveedor_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["reserva_oid"] = self.reserva_oid;
			

				
					dictionary["numLicencia"] = self.numLicencia;
				

				
					dictionary["categoria"] = self.categoria?.rawValue;
				

				
					dictionary["estado"] = self.estado?.rawValue;
				

					dictionary["proveedor_oid"] = self.proveedor_oid;
			
						
				return dictionary;
			}
		}
		
	