	
		//
		// FacturaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class FacturaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var fecha: NSDate?;
				    	 
		 
				var esPagada: Bool?;
				    	 
		 
				var esAnulada: Bool?;
				    	 
		 
				var cliente_oid: String?;
				    	 
		 
				var lineaFactura: [LineaFacturaDTO]?;
				    	 
		 
				var total: Float?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["fecha"] = self.fecha?.toString();
				

				
					dictionary["esPagada"] = self.esPagada;
				

				
					dictionary["esAnulada"] = self.esAnulada;
				

					dictionary["cliente_oid"] = self.cliente_oid;
			

					dictionary["lineaFactura"] = NSNull();
					if (self.lineaFactura != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.lineaFactura!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["lineaFactura"] = arrayOfDictionary;
					}
			

				
					dictionary["total"] = self.total;
				
						
				return dictionary;
			}
		}
		
	