	
		//
		// LineaFacturaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class LineaFacturaDTO 	    {
		 
				var factura_oid: Int?;
				    	 
		 
				var numLinea: Int?;
				    	 
		 
				var reserva_oid: Int?;
				    	 
		 
				var precio: Double?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["factura_oid"] = self.factura_oid;
			

				
					dictionary["numLinea"] = self.numLinea;
				

					dictionary["reserva_oid"] = self.reserva_oid;
			

				
					dictionary["precio"] = self.precio;
				
						
				return dictionary;
			}
		}
		
	